name: WalletAndroid-SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Configuration environment
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - rc
          - prod

env:
  PACKAGE_TYPE: "aar"
  GRADLE_VERSION: "7.5"
  JAVA_VERSION: "17"
  ARTIFACT_PATH: "VCL/build/outputs"
  ANDROID_NEXUS_SIGNING_KEY_ID: ${{ secrets.ANDROID_NEXUS_SIGNING_KEY_ID }}
  ANDROID_NEXUS_SIGNING_PWD: ${{ secrets.ANDROID_NEXUS_SIGNING_PWD }}
  ANDROID_NEXUS_OSSRH_USERNAME: ${{ secrets.ANDROID_NEXUS_OSSRH_USERNAME }}
  ANDROID_NEXUS_OSSRH_PWD: ${{ secrets.ANDROID_NEXUS_OSSRH_PWD }}
  ANDROID_NEXUS_STAGING_PROFILE_ID: ${{ secrets.ANDROID_NEXUS_STAGING_PROFILE_ID }}
  ANDROID_NEXUS_PRIVATE_KEY: ${{ secrets.ANDROID_NEXUS_PRIVATE_KEY }}
  GLOBAL_ENV: ${{ github.event_name == 'push' && format('{0}', 'dev') || inputs.environment }}

jobs:
  test-android-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v4
